# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: struct.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='struct.proto',
  package='proto',
  serialized_pb='\n\x0cstruct.proto\x12\x05proto\"+\n\x05\x42oard\x12\"\n\x06\x65ntity\x18\x01 \x03(\x0b\x32\x12.proto.BoardEntity\"V\n\x0b\x42oardEntity\x12\x1d\n\x06\x61uthor\x18\x01 \x02(\x0b\x32\r.proto.Person\x12\x0c\n\x04post\x18\x02 \x02(\t\x12\x0c\n\x04link\x18\x03 \x03(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x02(\t\"\'\n\x06Person\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0f\n\x07surname\x18\x02 \x01(\t')




_BOARD = _descriptor.Descriptor(
  name='Board',
  full_name='proto.Board',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entity', full_name='proto.Board.entity', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=23,
  serialized_end=66,
)


_BOARDENTITY = _descriptor.Descriptor(
  name='BoardEntity',
  full_name='proto.BoardEntity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='author', full_name='proto.BoardEntity.author', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='post', full_name='proto.BoardEntity.post', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='link', full_name='proto.BoardEntity.link', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='proto.BoardEntity.data', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=68,
  serialized_end=154,
)


_PERSON = _descriptor.Descriptor(
  name='Person',
  full_name='proto.Person',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='proto.Person.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='surname', full_name='proto.Person.surname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=156,
  serialized_end=195,
)

_BOARD.fields_by_name['entity'].message_type = _BOARDENTITY
_BOARDENTITY.fields_by_name['author'].message_type = _PERSON
DESCRIPTOR.message_types_by_name['Board'] = _BOARD
DESCRIPTOR.message_types_by_name['BoardEntity'] = _BOARDENTITY
DESCRIPTOR.message_types_by_name['Person'] = _PERSON

class Board(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BOARD

  # @@protoc_insertion_point(class_scope:proto.Board)

class BoardEntity(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BOARDENTITY

  # @@protoc_insertion_point(class_scope:proto.BoardEntity)

class Person(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PERSON

  # @@protoc_insertion_point(class_scope:proto.Person)


# @@protoc_insertion_point(module_scope)
